export const DEVICE_TYPES = [
  'غسالة',
  'ثلاجة',
  'بوتاجاز',
  'سخان',
  'تكييف',
  'ميكروويف',
  'غسالة أطباق',
] as const;

// Shared customer-facing labels. The manager accepts free text, so "أخرى" remains available in the forms.
export const BRAND_OPTIONS = [
  'سامسونج',
  'LG',
  'شارب',
  'توشيبا',
  'زانوسي',
  'يونيون إير',
  'فريش',
  'وايت ويل',
  'أريستون',
  'بيكو',
  'هوفر',
  'إنديست',
  'كريازي',
  'تورنيدو',
  'بوش',
  'سيمنز',
  'ميلا',
  'باناسونيك',
  'دايو',
  'كاريير',
  'يونيون تك',
  'وايت بوينت',
] as const;
